#!/bin/sh

clear
./tests.py && echo "Watching for python file changes..."

watchmedo shell-command --patterns="*.py" --recursive \
  --command="clear; echo \"Testing...\"; ./tests.py && echo \"Watching for python file changes...\""
