#!/bin/sh

clear
./compile-protobuf && echo "Watching for protobuf file changes..."

watchmedo shell-command --patterns="*.proto" --recursive \
  --command="clear; echo \"Compiling...\"; ./compile-protobuf && clear && echo \"protobufs compiled\""
