#!/bin/sh

clear
./tests.py && clear && echo "Watching for python file changes..."

watchmedo shell-command --patterns="*.py" --recursive \
  --command="clear; echo \"Testing...\"; ./tests.py && clear && echo \"tests ok\""
